# Generated by Django 3.1.6 on 2022-08-08 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gym.member'),
        ),
    ]
