# Generated by Django 3.1.6 on 2022-08-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20220808_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='Process',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Process',
            field=models.CharField(max_length=500),
        ),
    ]
