# Generated by Django 4.2.7 on 2024-02-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_trainer_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
